package test.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Orderdetails;

public interface OrderdetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("ordernumber") Integer ordernumber, @Param("productcode") String productcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated
     */
    int insert(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated
     */
    Orderdetails selectByPrimaryKey(@Param("ordernumber") Integer ordernumber, @Param("productcode") String productcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated
     */
    List<Orderdetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Orderdetails record);
}