package test.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Payments;

public interface PaymentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("customernumber") Integer customernumber, @Param("checknumber") String checknumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    int insert(Payments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    Payments selectByPrimaryKey(@Param("customernumber") Integer customernumber, @Param("checknumber") String checknumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    List<Payments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Payments record);
}