package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table productlines
 */
public class Productlines {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlines.productLine
     *
     * @mbg.generated
     */
    private String productline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlines.textDescription
     *
     * @mbg.generated
     */
    private String textdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlines.htmlDescription
     *
     * @mbg.generated
     */
    private String htmldescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlines.image
     *
     * @mbg.generated
     */
    private byte[] image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlines.productLine
     *
     * @return the value of productlines.productLine
     *
     * @mbg.generated
     */
    public String getProductline() {
        return productline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlines.productLine
     *
     * @param productline the value for productlines.productLine
     *
     * @mbg.generated
     */
    public void setProductline(String productline) {
        this.productline = productline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlines.textDescription
     *
     * @return the value of productlines.textDescription
     *
     * @mbg.generated
     */
    public String getTextdescription() {
        return textdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlines.textDescription
     *
     * @param textdescription the value for productlines.textDescription
     *
     * @mbg.generated
     */
    public void setTextdescription(String textdescription) {
        this.textdescription = textdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlines.htmlDescription
     *
     * @return the value of productlines.htmlDescription
     *
     * @mbg.generated
     */
    public String getHtmldescription() {
        return htmldescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlines.htmlDescription
     *
     * @param htmldescription the value for productlines.htmlDescription
     *
     * @mbg.generated
     */
    public void setHtmldescription(String htmldescription) {
        this.htmldescription = htmldescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlines.image
     *
     * @return the value of productlines.image
     *
     * @mbg.generated
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlines.image
     *
     * @param image the value for productlines.image
     *
     * @mbg.generated
     */
    public void setImage(byte[] image) {
        this.image = image;
    }
}