package test.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table orders
 */
public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderNumber
     *
     * @mbg.generated
     */
    private Integer ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderDate
     *
     * @mbg.generated
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.requiredDate
     *
     * @mbg.generated
     */
    private Date requireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shippedDate
     *
     * @mbg.generated
     */
    private Date shippeddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customerNumber
     *
     * @mbg.generated
     */
    private Integer customernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderNumber
     *
     * @return the value of orders.orderNumber
     *
     * @mbg.generated
     */
    public Integer getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderNumber
     *
     * @param ordernumber the value for orders.orderNumber
     *
     * @mbg.generated
     */
    public void setOrdernumber(Integer ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderDate
     *
     * @return the value of orders.orderDate
     *
     * @mbg.generated
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderDate
     *
     * @param orderdate the value for orders.orderDate
     *
     * @mbg.generated
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.requiredDate
     *
     * @return the value of orders.requiredDate
     *
     * @mbg.generated
     */
    public Date getRequireddate() {
        return requireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.requiredDate
     *
     * @param requireddate the value for orders.requiredDate
     *
     * @mbg.generated
     */
    public void setRequireddate(Date requireddate) {
        this.requireddate = requireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shippedDate
     *
     * @return the value of orders.shippedDate
     *
     * @mbg.generated
     */
    public Date getShippeddate() {
        return shippeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shippedDate
     *
     * @param shippeddate the value for orders.shippedDate
     *
     * @mbg.generated
     */
    public void setShippeddate(Date shippeddate) {
        this.shippeddate = shippeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customerNumber
     *
     * @return the value of orders.customerNumber
     *
     * @mbg.generated
     */
    public Integer getCustomernumber() {
        return customernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customerNumber
     *
     * @param customernumber the value for orders.customerNumber
     *
     * @mbg.generated
     */
    public void setCustomernumber(Integer customernumber) {
        this.customernumber = customernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.comments
     *
     * @return the value of orders.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.comments
     *
     * @param comments the value for orders.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}