package test.model;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table products
 */
public class Products {
    /**
     * Database Column Remarks:
     *   产品代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.productCode
     *
     * @mbg.generated
     */
    private String productcode;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.productName
     *
     * @mbg.generated
     */
    private String productname;

    /**
     * Database Column Remarks:
     *   产品线
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.productLine
     *
     * @mbg.generated
     */
    private String productline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.productScale
     *
     * @mbg.generated
     */
    private String productscale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.productVendor
     *
     * @mbg.generated
     */
    private String productvendor;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.quantityInStock
     *
     * @mbg.generated
     */
    private Short quantityinstock;

    /**
     * Database Column Remarks:
     *   价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.buyPrice
     *
     * @mbg.generated
     */
    private BigDecimal buyprice;

    /**
     * Database Column Remarks:
     *   建议零售价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.MSRP
     *
     * @mbg.generated
     */
    private BigDecimal msrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.productDescription
     *
     * @mbg.generated
     */
    private String productdescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.productCode
     *
     * @return the value of products.productCode
     *
     * @mbg.generated
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.productCode
     *
     * @param productcode the value for products.productCode
     *
     * @mbg.generated
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.productName
     *
     * @return the value of products.productName
     *
     * @mbg.generated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.productName
     *
     * @param productname the value for products.productName
     *
     * @mbg.generated
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.productLine
     *
     * @return the value of products.productLine
     *
     * @mbg.generated
     */
    public String getProductline() {
        return productline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.productLine
     *
     * @param productline the value for products.productLine
     *
     * @mbg.generated
     */
    public void setProductline(String productline) {
        this.productline = productline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.productScale
     *
     * @return the value of products.productScale
     *
     * @mbg.generated
     */
    public String getProductscale() {
        return productscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.productScale
     *
     * @param productscale the value for products.productScale
     *
     * @mbg.generated
     */
    public void setProductscale(String productscale) {
        this.productscale = productscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.productVendor
     *
     * @return the value of products.productVendor
     *
     * @mbg.generated
     */
    public String getProductvendor() {
        return productvendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.productVendor
     *
     * @param productvendor the value for products.productVendor
     *
     * @mbg.generated
     */
    public void setProductvendor(String productvendor) {
        this.productvendor = productvendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.quantityInStock
     *
     * @return the value of products.quantityInStock
     *
     * @mbg.generated
     */
    public Short getQuantityinstock() {
        return quantityinstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.quantityInStock
     *
     * @param quantityinstock the value for products.quantityInStock
     *
     * @mbg.generated
     */
    public void setQuantityinstock(Short quantityinstock) {
        this.quantityinstock = quantityinstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.buyPrice
     *
     * @return the value of products.buyPrice
     *
     * @mbg.generated
     */
    public BigDecimal getBuyprice() {
        return buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.buyPrice
     *
     * @param buyprice the value for products.buyPrice
     *
     * @mbg.generated
     */
    public void setBuyprice(BigDecimal buyprice) {
        this.buyprice = buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.MSRP
     *
     * @return the value of products.MSRP
     *
     * @mbg.generated
     */
    public BigDecimal getMsrp() {
        return msrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.MSRP
     *
     * @param msrp the value for products.MSRP
     *
     * @mbg.generated
     */
    public void setMsrp(BigDecimal msrp) {
        this.msrp = msrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.productDescription
     *
     * @return the value of products.productDescription
     *
     * @mbg.generated
     */
    public String getProductdescription() {
        return productdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.productDescription
     *
     * @param productdescription the value for products.productDescription
     *
     * @mbg.generated
     */
    public void setProductdescription(String productdescription) {
        this.productdescription = productdescription;
    }
}