package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tokens
 */
public class Tokens {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tokens.s
     *
     * @mbg.generated
     */
    private String s;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tokens.s
     *
     * @return the value of tokens.s
     *
     * @mbg.generated
     */
    public String getS() {
        return s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tokens.s
     *
     * @param s the value for tokens.s
     *
     * @mbg.generated
     */
    public void setS(String s) {
        this.s = s;
    }
}